### ISSUE TITLE
大佬实在太nb辣

### ISSUE THREAD

**Issue by IPlayGenji6** [Italink/QNeumorphism#3]
看了大佬你的文章，像图形方向发展从Qt开始可以吗，有没有学习发展路线建议

**Comment by Italink** [comment]
图形也有很多方向，如果你更关注效果，那么其实有一定程序基础就够了，短期不用太深入，如果你想往VR、AR、XR、音视频、三维软件开发，游戏引擎、图形这种代码开发方向的话，Qt是一個很好的过渡框架，借助它完善的文档和高可读性的代码，你能在里面学到很多大型系统架构的知识，如果没有非常扎实的基础，这些知识是很难上手的，Qt可以将门槛降的很低，把学习曲线变平缓，即使这样，如果你确定要在这个方向持续发展，一定是需要投入大量时间和精力的，并且它的难度很大，短期也很难看到成效，但技术竞争力也是毋庸置疑的

**Comment by IPlayGenji6** [comment]
明白了，十分感谢
